---
title: "R Notebook"
output:
  html_notebook: default
  pdf_document: default
---

```{r}
library(party)
library(randomForest)
library(caret)
library(dplyr)
library(ROCR)
library(ggplot2)
library(MLmetrics)
```

```{r}
#set.seed(1)
train <- read.csv('~/documents/fordham/March Madness 2017/newdata-1.csv', head = TRUE, sep = ",")
train <- na.roughfix(train)
train$result <- as.factor(train$result)
train$season <- as.factor(train$season)
train$team1_rpi <- as.numeric(train$team1_rpi)
train$team2_rpi <- as.numeric(train$team2_rpi)
str(train)

test <- read.csv('~/documents/fordham/March Madness 2017/newdata2017.csv', head = TRUE, sep = ",")
test <- na.roughfix(test)
test$team1_rpi <- as.numeric(test$team1_rpi)
test$team2_rpi <- as.numeric(test$team2_rpi)
str(test)
```


```{r}
extractFeatures <- function(data) {
  varNames <- names(data)
  varNames <- varNames[!varNames %in% c('result','game_id','season')]
  selection <- data[,varNames]
  #print (varNames)
  return (selection)
}
extractFeatures_test <- function(data) {
  varNames <- names(data)
  varNames <- varNames[!varNames %in% c('game_id','season')]
  selection <- data[,varNames]
  #print (varNames)
  return (selection)
}

mtryz <- tuneRF(extractFeatures(train),as.factor(train$result), ntreeTry=5000,stepFactor=1.5,improve=0.01, trace=TRUE, plot=TRUE)
best.m <- mtryz[mtryz[, 2] == min(mtryz[, 2]), 1]
```

```{r}
rf <- randomForest(extractFeatures(train),as.factor(train$result), ntree = 5000, mtry = best.m, importance = T, keep.forest = T, oob.prox = F)

print (rf)

varImpPlot(rf, sort = T, main = "Variable Importance", n.var = 10)
p <- ggplot(featureImportance, aes(x = reorder(Feature, Importance), y = Importance)) +
  geom_bar(stat = 'identity', fill = "#53cfff") +
  coord_flip() +
  theme_light(base_size = 20) +
  xlab("") +
  ylab("Importance") +
  ggtitle("Predictor Importance\n") +
  theme(plot.title = element_text(size = 18))

plot(rf)
#print (p)

```


```{r}
names(test)
print('----')
names(extractFeatures_test(test))
```

```{r}
submission <- data.frame(game_id = test$game_id)
#submission$result <- test$result
submission$predicted <- predict(rf, extractFeatures_test(test))
probs <- predict(rf, extractFeatures_test(test), type = 'prob')
perf = prediction(probs[,2], submission$predicted)
auc = performance(perf, "auc")
pred3 = performance(perf, "tpr","fpr")
plot(pred3,main="ROC Curve for Random Forest",col=2,lwd=2)
abline(a=0,b=1,lwd=2,lty=2,col="gray")

#confusionMatrix(data = submission$predicted,
 #               reference = submission$result,
  #              positive = "1")

submission$prob <- probs[,2]
print(submission)
```

```{r}
#print (probs)
print (probs)
```
```{r}
submission2017 <- data.frame(id = submission$game_id, prob = submission$prob)
print (submission2017)
```
```{r}
write.csv(submission2017, file = 'OneBillionDollars.csv', na = "NA", row.names = FALSE)
```

```{r}
#submission$resultint <- as.integer(as.character(submission$result)) 
#submission$logloss <- -((submission$predicted*log(submission$prob))+((1-submission$predicted)*log(1-submission$prob)))

#print (submission)

#mean(submission$logloss)
#plot(submission$prob,submission$logloss)

#submission[order(-submission$logloss),]
#print (submission)
```



